- name: install_nginx | add nginx repository signing key
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present 

- name: install_nginx | add repository to sources
  apt_repository:
    repo: deb http://nginx.org/packages/debian/ {{ ansible_distribution_release }} nginx
    state: present
    filename: nginx
    update_cache: yes

- name: install_nginx | download and install nginx
  apt: 
    name: nginx
    state: present
    update_cache: yes
    
