VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "spud206/Debian"
  config.vm.network "public_network", ip: "192.168.107.6"
  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 2
  end
  #
  # Run Ansible
  #
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end
